services:
  locust-master:
    image: locustio/locust:2.31.5
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --master
      --web-host 0.0.0.0

  locust-worker:
    image: locustio/locust:2.31.5
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/locustfile.py
      --worker
      --master-host locust-master
    depends_on:
      - locust-master
